[build]
  command = "yarn docs:build"
  publish = ".vitepress/dist"

[build.environment]
  NODE_VERSION = "20.19.0"

[[headers]]
  for = "/*"
  [headers.values]
    connect-src = "https://api.airtable.com"
